### PR TITLE
Change `componentWillMount` to `UNSAFE_componentWillMount`

### PR DESCRIPTION
**Pull request by joshfry**
Fix for `Warning: componentWillMount has been renamed, and is not recommended for use.`

### CODE REVIEW

**Comment by rodomeista** [comment]
Came here to do the same, thanks for taking care of it 🍻

Let's hope this gets merged in soon so we can suppress these pesky warnings

**Comment by vasklund** [comment]
I'm just a random bystander, but from my understanding this PR won't be accepted. See e.g. #57.

**Comment by tyscorp** [comment]
Accepting this PR will remove the warnings and keep the behavior the same. (at least for React v16.x)

**Comment by lourd** [comment]
Hi @joshfry, nice to meet you, thanks for the PR.

I've added a commit updating the tests and dependencies to be able to use the new API name. This will be a major version bump on the library as it's a breaking change. All dependent libraries will need to use the new version (v2), and all end users will have to upgrade their projects to React v16.9 as well.

Does that sound correct and good to everyone?

**Comment by joshfry** [comment]
That sounds perfect. Thank you!

**Comment by lourd** [comment]
Just published under v2.0.0 👍

**Pull request merged**
