### PR TITLE
chore: update shallowequal

### PR DESCRIPTION
**Pull request by ScriptedAlchemy**
Resolves tree-shaking issues

### CODE REVIEW

**Comment by ScriptedAlchemy** [comment]
@gaearon @lourd just tagging you so it doesn't fall through the cracks. I know you are busy ❤️

**Comment by lourd** [comment]
Hey Zack, thanks for the PR and ping.

Can you explain to me what this solves? Projects using this library would
automatically use 1.1.0 of shallowequal as far as I understand how semver
and the the ^ operator works.

**Comment by ScriptedAlchemy** [comment]
@lourd so i thought, but from running bundle analysis - i see webpack is not tree-shaking it 

```
shallowequal (Found 2 resolved, 2 installed, 3 depended. Latest 1.1.0.)
  1.0.2 ~/react-side-effect/~/shallowequal
    ecom-web-app@1.0.0 -> react-helmet@~5.2.0 -> react-side-effect@^1.1.0 -> shallowequal@^1.0.1
  1.1.0 ~/shallowequal
    ecom-web-app@1.0.0 -> react-focus-lock@^1.13.2 -> react-clientside-effect@^1.0.0 -> shallowequal@^1.1.0
    ecom-web-app@1.0.0 -> react-hot-loader@^4.12.10 -> shallowequal@^1.1.0
```

**Comment by lourd** [comment]
Thanks for the additional info.

If I install react-helmet, react-focus-lock, and react-hot-loader, and then list the installed packages, there's only one version of shallowequal installed — 1.1.0. It's not up to webpack to dedupe the compatible installed modules, it's the installer. Webpack is behaving as intended by not dropping one of the versions.

```sh
mkdir test
cd test
npm install react-helmet react-focus-lock react-hot-loader
npm ls | grep shallowequal
> │   └── shallowequal@1.1.0 deduped
>  ├── shallowequal@1.1.0
```

I'd recommend double checking your project's yarn.lock or package-lock.json. If that specifically requires separate versions, then separate versions will be installed every time.

**Comment by ScriptedAlchemy** [comment]
Thank you! Appreciate the information! Learned something here

**Pull request closed without merging**
