### PR TITLE
Fix prototype chain

### PR DESCRIPTION
**Pull request by lo1tuma**

### CODE REVIEW

**Comment by lo1tuma** [comment]
Any feedback so far?

**Comment by gaearon** [comment]
Apologies for the delay, I'm a bit sick.

**Comment by lo1tuma** [comment]
Nothing to apologize for. Get well soon.

**Comment by gaearon** [comment]
Out in 1.0.2.

**Comment by lo1tuma** [comment]
Awesome. Thank you :beers:.

**Comment by gaearon** [comment]
Thank you for fixing it and creating infra!

**Pull request merged**
